#! python


def build(ctx):
    # Loop over all metrics and 2/3 agent markets
    all_metrics = [
        "state_profitability",
        "weighted_profitability",
        "best_response_share",
        "avg_profit",
        "avg_price",
        "nash_equilibrium",
    ]
    for n_agents in [2, 3]:
        for metric in all_metrics:
            for with_super_star in ["with", "without"]:
                ctx(
                    features="run_py_script",
                    source="plot_heatmaps.py",
                    deps=ctx.path_to(ctx, "OUT_DATA", f"grid_{n_agents}_agents.pickle"),
                    target=ctx.path_to(
                        ctx,
                        "OUT_FIGURES",
                        f"heatmap_{metric}_{with_super_star}_super_star_{n_agents}_n_agents.pdf",
                    ),
                    append=[str(n_agents), metric, with_super_star],
                    name=f"plot_heatmaps_{n_agents}",
                )

    # Plot deviation figures
    for n_agents in [2, 3]:
        ctx(
            features="run_py_script",
            source="plot_deviation.py",
            deps=[
                ctx.path_to(
                    ctx,
                    "OUT_ANALYSIS",
                    f"array_deviation_simulations_{n_agents}_agents.pickle",
                ),
                ctx.path_to(ctx, "IN_MODEL_SPECS", "deviation_simulation.json"),
                ctx.path_to(
                    ctx,
                    "IN_SIMULATION_PARAMETER",
                    f"parameter_{n_agents}_agent_base.json",
                ),
            ],
            target=ctx.path_to(
                ctx, "OUT_FIGURES", f"deviation_plot_{n_agents}_agents.pdf"
            ),
            append=[str(n_agents)],
            name=f"plot_deviation_{n_agents}",
        )

    # Plot human v algo bar plot
    ctx(
        features="run_py_script",
        source="plot_human_v_algo_bar_charts.py",
        deps=[
            ctx.path_to(
                ctx,
                "OUT_DATA",
                f"entire_price_grid_avg_prices_2_agents.pickle",
            ),
            ctx.path_to(
                ctx,
                "OUT_DATA",
                f"entire_price_grid_avg_prices_3_agents.pickle",
            ),
            ctx.path_to(
                ctx,
                "OUT_DATA",
                f"super_star_avg_prices_2_agents.pickle",
            ),
            ctx.path_to(
                ctx,
                "OUT_DATA",
                f"super_star_avg_prices_3_agents.pickle",
            ),
            ctx.path_to(
                ctx,
                "OUT_DATA",
                f"data_group_level.pickle",
            ),
        ],
        target=ctx.path_to(
            ctx, "OUT_FIGURES", f"bar_plot_human_v_algos.pdf"
        ),
        name=f"plot_human_v_algo_bar_charts",
    )

    # Plot experimental bar chart
    ctx(
        features="run_py_script",
        source="plot_bar_charts_experiments.py",
        deps=[

            ctx.path_to(
                ctx,
                "OUT_DATA",
                f"data_group_level.pickle",
            )
        ],
        target=ctx.path_to(
            ctx, "OUT_FIGURES", f"bar_plot_experiments_winning_price.pdf"
        ),
        name=f"plot_bar_charts_experiments",
    )